### ISSUE TITLE
extreme high CPU/GPU usage

### ISSUE THREAD

**Issue by AmySakuraChan** [flamewave000/discord-overlay#12]
It works, except a little bit flickering, but it does its job quite fine, except the cpu usage is extremely high. Without the program i got about 10% of cpu usage and only have open Discord and my Browser.
But while the program is open the CPU usage raises up to 93%.
Also when i force the GPU to manage the application, it gets high usage.

I got an Intel Core i5 9300H and NVidia RTX 2060, so its a decent cpu/gpu, may you find a way how to fix this high cpu usage but i am so thankful that you created the little program and appreciate it very much :)

**Comment by flamewave000** [comment]
This is definitely abnormal, I just checked my CPU usage and it sits low at between 5-10% usage. Either way, I'll put a frame limiter option in for this. It will default to 10 FPS, but can be 5/10/20/30 FPS.
