### ISSUE TITLE
Editing Usernames on the fly

### ISSUE THREAD

**Issue by lacksfish** [flamewave000/discord-overlay#13]
I've been looking over the code base, but I did not find where the usernames are being pulled from and provided to the application.

Could you point me to the lines of code where usernames are imported, and where they are handled to be displayed?

I want to extent your program so that I edit the usernames with a certain RegEx. I will code that myself obviously, but if you could help me get started it would be much appreciated. Where should I start looking for the handling of usernames?

Best regards!

**Comment by flamewave000** [comment]
I do not import anything. I simply create a DirectX Device Context. The this works is that Discord can pull the list of all applications that have registered a context with the GPU, this is normally only done by Games so it is a safe assumption to make.

It then grabs that context and renders its own UI over top of the device's render target. This means that my `Discord Overlay` program has Zero interaction with Discord. Instead Discord is highjacking my render context "without my knowledge" to render their own stuff.

The only way to make any changes as it pertains to the content shown, must be done within Discord itself.
