### ISSUE TITLE
Not detected anymore by discord

### ISSUE THREAD

**Issue by AmySakuraChan** [flamewave000/discord-overlay#14]
in the add game to discord list the program isnt recognized and so on the program not orking anymore at all :/

**Comment by flamewave000** [comment]
You need to make sure the Discord Overlay program is running before you try to search for it in Discord. I just tested it with latest Discord and Windows 10 and it is still working as expected.

**Comment by AmySakuraChan** [comment]
i did.. no chance :/ maybe new discord update broke it?

**Comment by flamewave000** [comment]
Unfortunately I have no control over Discord's ability to find the application. You could maybe try running Discord as administrator, but otherwise I'm sadly unable to help.

**Comment by AmySakuraChan** [comment]
discord now detects it again, but still not working anymore :/ even with the settings from one youtube vicdeo that worked before

**Comment by flamewave000** [comment]
Sadly discord is not the most reliable with it's overlay. There have been times where it won't display for me until I restart my computer. It's unfortunately out of my hands since I have to rely on Discord to actually grab my program's context and draw onto it.
