### ISSUE TITLE
overlay not appear on Fullscreen or Borderless while playing game,you need to play it on window screen

### ISSUE THREAD

**Issue by Dicktrainer1412** [flamewave000/discord-overlay#15]
I have this issue when playing SOMA
I love your product its save me a lot of work
btw do you have a plan to have an auto startup on this thing, i will suggest it because i just want this to be my default

**Comment by flamewave000** [comment]
Fullscreen applications cannot be supported. I cannot display my window on-top of another window that has taken full control of the monitor. You will want to try and get Discord to render to the program itself instead.
If you mean you want Discord Overlay to always start up with windows you can do the following:

1. Create a shortcut of the program
    - Right-click program
    - Select "Create shortcut"
2. Open the Run window by right-clicking the Windows Start button and select "Run"  
![image](https://user-images.githubusercontent.com/3588046/147779660-3fcd0248-f64a-4b08-9d99-a897e5b5a12c.png)
3. Type this and hit enter: `shell:startup`  
![image](https://user-images.githubusercontent.com/3588046/147779714-d159d9ce-c718-43c1-b70f-85aa24955618.png)
4. Copy or move the shortcut into the folder that opens.

Windows will automatically run any program who's shortcut is in this directory.

**Comment by Dicktrainer1412** [comment]
that sad,tks for respond
kinda weird that when I played League of legend the borderless mode working
but the borderless on SOMA not working

**Comment by flamewave000** [comment]
@Dicktrainer1412 Windows has the option for Windowed Borderless. In that case it is still a regular window but maximized and without a border or titlebar. It is possible that SOMA is just toggling the "Fullscreen" flag which gives the program sole use of the monitor when focused and prevents my window from displaying on top of it.
