### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ThePrimoris** [flamewave000/discord-overlay#18]
Downloaded it and set it up and it's not showing any overlay.

**Comment by flamewave000** [comment]
It is maintained. I use it every week when I run my online D&D games.

Please make sure to follow the instructions for setting it up carefully. Also, it can sometimes take up to 5 minutes Ford Discord to actually start drawing the overlay. If it doesn't work, you can shutdown both programs, start Discord Overlay and then start Discord. That will sometimes get Discord to work properly.
