### ISSUE TITLE
Make it unclickable

### ISSUE THREAD

**Issue by ofsaleem** [flamewave000/discord-overlay#2]
I love this so much, thank you so much for writing it! I have a feature request though, is it possible to make the overlay window unclickable? it's mostly there but i find it's still possible, especially in a crowded voice channel, to click on someone's name or picture and then the overlay window becomes active, which is an issue. is there any way to make it completely unresponsive to all input?

**Comment by flamewave000** [comment]
This is now possible in the latest 2.0 release. Feel free to try it out. Beware, the overlay window cannot be moved or resized until you turn the clicking back on. So set it, then disable the clicking in the host window and enjoy :)
