### ISSUE TITLE
Overlay doesnt update if you unmute yourself

### ISSUE THREAD

**Issue by ogkimra** [flamewave000/discord-overlay#21]
Hey, I was just trying out your project! Seems really cool. 
When I mute + deafen myself and then unmute + undeafen then the overlay still shows that I am muted

![image](https://github.com/flamewave000/discord-overlay/assets/32086892/1fe187d0-578f-4812-9475-96e97ace518f)

![image](https://github.com/flamewave000/discord-overlay/assets/32086892/a7963b94-2309-4fe8-a9e7-ef5e9ba9e214)

I hope you could fix this
Thanks again

**Comment by flamewave000** [comment]
So I've seen this sometimes happen as well. It seems to be an issue with Discord's overlay. The UI is still updating and showing active speakers and such, but Discord is not clearing that icon from the screen. Unfortunately I don't have any control over what Discord draws over my program, so I'm sad to say this isn't something I can fix.

The work around when this happens is to just restart the overlay program. If you have the "Save Window Positions" enabled, you can restart the app and the window will be the same size and position as before it was closed.
