### ISSUE TITLE
Not showing overlay

### ISSUE THREAD

**Issue by Woodyspin** [flamewave000/discord-overlay#22]
So been using this for a while now and it worked great, especially with the way I have my setup, it was perfect! However, now it just doesn't want to show the overlay at all...

from what I see everything is on as it should be and it's detecting the game, I'm in a voice channel and nothing! Any ideas at all?

**Comment by flamewave000** [comment]
Unfortunately Discord will sometimes stop playing nice after an update. It can be tricky to get it working again. Sometimes just terminating Discord and restarting it works, or restarting your computer will do it. You could also try disabling the overlay, restarting Discord, and then re-enable it. It can also sometimes take a while for it to connect, so try waiting maybe 5 minutes and see if Discord finds the program.

It is still working for me, so it is likely just Discord being unfriendly on your computer at the moment.
