### ISSUE TITLE
No contents showed on neither discord overlay host. NOR the other window. + An error shows up if running the app for the 2nd time. 

### ISSUE THREAD

**Issue by estrizal** [flamewave000/discord-overlay#23]
1 > I downloaded and ran the exe as administrator
2> I tried followed the steps
Nothing showed up on either of the screen. 
closed and tried to reopen. got this error
Running discord PTB.

![image](https://github.com/flamewave000/discord-overlay/assets/87994109/b719d6fc-2062-43a1-bbcb-e6737b12ee37)

EDIT:- It works in normal version of discord though. just tried it. 
Also, Could you add a feature for text too ?. like an option to get chat option to pre defined text channels if you press a particular hot key. 

Edit2:- But while running the 2nd time. this error still comes. I have to edit the json file and remove excessive "}" to get it working again.

**Comment by flamewave000** [comment]
The error you're seeing will be fixed in V2.3 and was originally reported in #25 

Unfortunately I have no control over the overlay that Discord creates. Their app grabs my Graphics Canvas and they draw their own UI over it, so there's not really anything I can do about chat channels or shortcuts.
