### ISSUE TITLE
Resolving Overlay Windows in Alt+Tab View on Windows

### ISSUE THREAD

**Issue by manjit24** [flamewave000/discord-overlay#24]
When pressing Ctrl+Alt+Tab, two windows appear due to an overlay. Is there a way to hide these in the recent view? They also show up when pressing Alt+Tab. Please correct this issue.
<img width="574" alt="image" src="https://github.com/flamewave000/discord-overlay/assets/40887412/9bf66b43-5453-4e2e-8325-c0ac3c9fbec0">

**Comment by awh018** [comment]
I just submitted a request for this behavior to be added, maybe it can be an option?
