### ISSUE TITLE
Direct X Host Issue

### ISSUE THREAD

**Issue by fightmesun** [flamewave000/discord-overlay#25]
When I first intially launched it work but afterwards, I get a small window with this messgae.

![image](https://github.com/flamewave000/discord-overlay/assets/46666382/03627c6f-c97b-446f-8819-484a32c3427e)

**Comment by GoofyWarriorGuy** [comment]
I am also seeing this issue. Is there a fix?

**Comment by flamewave000** [comment]
Current workaround is to delete the `settings.json` file. I haven't had a chance yet to look into the issue.
