### ISSUE TITLE
Cannot resize host window: Object referenced not set to an instance of an object

### ISSUE THREAD

**Issue by laundmo** [flamewave000/discord-overlay#28]
Running the overlay and then resizing the overlay host window, as discord complains it is too small, causes this issue.

![image](https://github.com/flamewave000/discord-overlay/assets/24855949/9df571ad-ad02-48f2-8267-9d3b32faffd3)

This is a distinct issue to the recently fixed one which could be worked around by deleting settings.json

**Comment by flamewave000** [comment]
Huh, I was focusing on the overlay window I didn't think to retest the host window lol. I'll get a 2.3.1 out in a few minutes
