### ISSUE TITLE
Request: Visible Overlay process for VR injection

### ISSUE THREAD

**Issue by awh018** [flamewave000/discord-overlay#30]
Is there a way we can get the overlay window visible in the taskbar/alt tab, so we can inject into a VR session?

**Comment by flamewave000** [comment]
This was actually removed by request of several users. I can look into adding an option to re-enable it though.

**Comment by awh018** [comment]
Yeah I just saw that, I downloaded ver 2.2, and it does allow me to inject perfectly. And I don't mind having the extra window on the Alt-Tab or taskbar. Thanks

**Comment by flamewave000** [comment]
I'll see if I can get a v2.4 for you to try with that as an option. v2.2 has an issue with saving settings that can cause it to not be able to startup.

**Comment by flamewave000** [comment]
Please give this build a try. If it works for you, I'll push it into the releases :+1:

[Discord.Overlay_2.3.2.zip](https://github.com/flamewave000/discord-overlay/files/14775685/Discord.Overlay_2.3.2.zip)

**Comment by awh018** [comment]
Seems to work great, thanks for the quick work!!

**Comment by ibigfire** [comment]
Thanks for doing this! For some reason it doesn't work for me and even selecting "Show Overlay in Taskbar" doesn't make the overlay appear in my taskbar.  I'm on Windows 10 if it helps.
