### ISSUE TITLE
overlay in the new version is not always on top

### ISSUE THREAD

**Issue by ofsaleem** [flamewave000/discord-overlay#4]
having an issue where the latest version (thanks for making it unclickable btw) does not stay on top of fullscreen windows for some reason. it seems like it works for borderless windowed but fullscreen doesnt work. testing it right now with dark souls 3 and i cant get it to stay on top of ds3 no matter what. tried with unclickable checked on and off and tried restarting discord, ds3, and the overlay

**Comment by flamewave000** [comment]
Unfortunately this is a thing in Windows. If a program is in actual FullScreen mode, no other windows can be on top of it. Steam and Discord get around this by highjacking the game's own canvas and drawing their UI onto the Game's screen. Sadly you won't be able to use my Overlay program unless the game is in Windowed mode.
