### ISSUE TITLE
Request: Show in tray

### ISSUE THREAD

**Issue by winterwulf** [flamewave000/discord-overlay#5]
Could it be possible to add an option to show the app icon only in the tray instead of the tool bar?

**Comment by flamewave000** [comment]
While it should be possible to achieve this without the window showing in the taskbar, I will need to investigate it. I only worry that Discord may not like it (Discord already doesn't like transparent windows).

**Comment by winterwulf** [comment]
I see, I appreciate :)

**Comment by flamewave000** [comment]
So I've looked into it and unfortunately the SharpDX library I'm using creates and owns the main window and I am unable to keep it out of the taskbar. I hope this is not a deal breaker for you and you can still enjoy the program. Thanks :)
